# Generated by Django 4.2 on 2023-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleData',
            fields=[
                ('sentenceNum', models.IntegerField(primary_key=True, serialize=False)),
                ('example1', models.CharField(max_length=50)),
                ('example2', models.CharField(max_length=50)),
                ('example3', models.CharField(max_length=50)),
            ],
        ),
    ]
